# Uncomment this line to define a global platform for your project
# platform :ios, '6.0'

source 'https://github.com/CocoaPods/Specs.git'

target '7-segment' do
pod 'OpenCV'

end

target '7-segmentTests' do

end

